[2023-11-20 10:58:49,021] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:02:59,903] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:02:59] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:02:59,914] WARNING add_product() L72   Erro ao adicionar product 'Guaraná', Não foi possível salvar novo item :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L72  
[2023-11-20 11:02:59,917] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:02:59] "[31m[1mPOST /product HTTP/1.1[0m" 400 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:03:09,367] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:03:09,508] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:03:11,751] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:03:11] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:03:11,761] WARNING add_product() L72   Erro ao adicionar product 'Guaraná', Não foi possível salvar novo item :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L72  
[2023-11-20 11:03:11,762] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:03:11] "[31m[1mPOST /product HTTP/1.1[0m" 400 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:00,811] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:00,943] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:40,476] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:40,602] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:52,852] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:09:52,983] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:00,080] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:10:00] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:00,090] WARNING add_product() L69   Erro ao adicionar product 'Guaraná', produto de mesmo nome e recipiente já salvo na base :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L69  
[2023-11-20 11:10:00,091] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:10:00] "[31m[1mPOST /product HTTP/1.1[0m" 409 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:32,674] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:32,803] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:41,026] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:10:41] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:41,041] WARNING add_product() L72   Erro ao adicionar product 'Guaraná', Não foi possível salvar novo item :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L72  
[2023-11-20 11:10:41,042] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:10:41] "[31m[1mPOST /product HTTP/1.1[0m" 400 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:57,253] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:10:57,379] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:05,555] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:05,721] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:14,107] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:14,280] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:16,957] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:11:16] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:16,966] WARNING add_product() L72   Erro ao adicionar product 'Guaraná', Não foi possível salvar novo item :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L72  
[2023-11-20 11:11:16,967] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:11:16] "[31m[1mPOST /product HTTP/1.1[0m" 400 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:28,841] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:28,967] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:32,381] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:11:32] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:11:32,390] WARNING add_product() L67   Erro ao adicionar product 'Guaraná', produto de mesmo nome e recipiente já salvo na base :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L67  
[2023-11-20 11:11:32,391] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 11:11:32] "[31m[1mPOST /product HTTP/1.1[0m" 409 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:12:59,173] INFO _log() L96    * Detected change in 'C:\\fabrica\\pessoal\\pos-full-stack\\mvp\\first-sprint\\back-end\\app.py', reloading - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 11:12:59,304] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 14:08:06,295] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 14:08:06] "GET /products HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 14:11:52,333] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 14:11:52] "GET /products HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 14:12:44,525] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 14:12:44] "OPTIONS /product HTTP/1.1" 200 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
[2023-11-20 14:12:44,533] WARNING add_product() L67   Erro ao adicionar product 'Guaraná', produto de mesmo nome e recipiente já salvo na base :/ - call_trace=C:\fabrica\pessoal\pos-full-stack\mvp\first-sprint\back-end\app.py L67  
[2023-11-20 14:12:44,535] INFO _log() L96   127.0.0.1 - - [20/Nov/2023 14:12:44] "[31m[1mPOST /product HTTP/1.1[0m" 409 - - call_trace=C:\Users\talit\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L96  
